Repository hmcts/rd-location-ref-api, pull requests merged in 2020-12, with the labels that each got.

#120 refactor: toggle off LRD API (RDCC-2011)
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
  charts/rd-location-ref-api/Chart.yaml
  charts/rd-location-ref-api/values.preview.template.yaml
  charts/rd-location-ref-api/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/util/CustomSerenityRunner.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/util/ToggleEnable.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/LrdAuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LrdApiClient.java
  src/integrationTest/resources/application-test.yml
  src/main/java/uk/gov/hmcts/reform/lrdapi/config/LaunchDarklyConfiguration.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/advice/ExceptionMapper.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/exception/ForbiddenException.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/FeatureToggleService.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/FeatureToggleServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/util/FeatureConditionEvaluation.java
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yml
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/advice/ExceptionMapperTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/FeatureToggleServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/util/FeatureConditionEvaluationTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-120

#121 feat:removed the unused files.
  src/main/java/uk/gov/hmcts/reform/lrdapi/config/JacksonConfiguration.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/config/RestTemplateConfiguration.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-121

#122 fix: flyway schema
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-122

#124 fix: Nightly Build fix
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/util/CustomSerenityRunner.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-124

#125 Add sync method call
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-125

#129 build: Upgraded versions to fix CVE-2020-13956 and CVE-2020-25638
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-129

#131 fix: RDCC-2102 IgnoreCase search for ccdcasetype and removed sequence
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsIntegrationTest.java
  src/integrationTest/resources/db/migration/V1_2__add_sequences.sql
  src/main/java/uk/gov/hmcts/reform/lrdapi/repository/ServiceToCcdCaseTypeAssocRepositry.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/repository/ServiceToCcdCaseTypeAssocRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-131

#137 Bump : RDCC-2017 Jar version upgrade
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-137

#138 Bump : RDCC-2017 Upgrade Jar Versions
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-138

#144 RDCC-2143: CVE-2020-8908 fix
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-144

#145 Create s2s secret
  infrastructure/main.tf
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-145
