Repository hmcts/rd-location-ref-api, pull requests merged in 2020-10, with the labels that each got.

#28 fix:Bum up Spring version for CVE
  build.gradle
  charts/rd-location-ref-api/Chart.yaml
  charts/rd-location-ref-api/values.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-28

#34 TF upgrade to 0.12.16 and Azure RM upgrade to 2.20.0 - Master
  infrastructure/main.tf
  infrastructure/provider.tf
  infrastructure/state.tf
  infrastructure/terraform.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-34

#26 feat: Static tables dataload through flyway LRD script(RDCC-1864)
  src/main/resources/db/migration/V1_1__init_tables.sql
  src/main/resources/db/migration/V1_2__add_sequences.sql
  src/main/resources/db/migration/V1_3__alter_LRD.sql
  src/main/resources/db/migration/V1_4__Insert_LRD.sql
  src/main/resources/db/migration/V1_5__services.sql
  src/main/resources/db/migration/V1_6__excption_table.sql
  src/main/resources/db/migration/V1_7__audit_table.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-26

#36 TF Upgrade to 13.3 and Azure RM to 2.25+ - Master
  infrastructure/.terraform-version
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-36

#37 fix:master build fix for enableDbMigration
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-37

#38 fix:master build fix for smoke test and s2s
  build.gradle
  charts/rd-location-ref-api/Chart.yaml
  charts/rd-location-ref-api/values.preview.template.yaml
  charts/rd-location-ref-api/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/config/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/controllers/GetWelcomeTest.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/LrdApiApplication.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/config/DataSourceConfig.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/RootController.java
  src/main/resources/bootstrap.yml
  src/smokeTest/java/uk/gov/hmcts/reform/lrdapi/SmokeTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-38

#47 fix:set current schema datasource
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1_2__add_sequences.sql
  src/main/resources/db/migration/V1_3__alter_LRD.sql
  src/main/resources/db/migration/V1_5__services.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-47

#58 Fix : Bump up and owasp update(RDCC-1933)
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-58

#62 fix: reverting postgres version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-62

#77 refactor: updated audit and exception table logging LRD (RDCC-1927)
  src/main/resources/db/migration/V1_8__alter_audit_exception_table.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-77

#88 feat:correcting the image name
  charts/rd-location-ref-api/Chart.yaml
  charts/rd-location-ref-api/values.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-88

#89 feat:added for security scan
  Jenkinsfile_nightly
  README.md
  audit.json
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-89

#93 refactor: Updated flyway for data-ingestion library changes
  src/main/resources/db/migration/V1_6__excption_table.sql
  src/main/resources/db/migration/V1_7__audit_table.sql
  src/main/resources/db/migration/V1_8__alter_audit_exception_table.sql
  src/main/resources/db/migrationAks/V2_1__service_to_ccd_case_type_assoc.sql
  src/main/resources/db/postgres/V1_8__adding_index_for_serviceCode_ccdServicename_constraint.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-93

#96 fix: schema issue fixed (RDCC-1924)
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/LrdAuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/SpringBootIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/repository/ServiceRepositoryTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/repository/ServiceToCcdCaseTypeAssocRepositoryTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LrdApiClient.java
  src/integrationTest/resources/application-test.yml
  src/integrationTest/resources/db/migration/V1_1__init_tables.sql
  src/integrationTest/resources/db/migration/V1_2__add_sequences.sql
  src/integrationTest/resources/db/migration/V1_3__alter_LRD.sql
  src/integrationTest/resources/db/migration/V1_5__services.sql
  src/integrationTest/resources/db/migration/V1_6__excption_table.sql
  src/integrationTest/resources/db/migration/V1_7__audit_table.sql
  src/integrationTest/resources/db/migration/V1_8__alter_audit_exception_table.sql
  src/integrationTest/resources/db/migrationAks/V2_1__service_to_ccd_case_type_assoc.sql
  src/main/resources/application.yaml
  src/test/resources/application.yml
  src/test/resources/db/migration/V1_10__service_to_ccd_case_type_assoc.sql
  src/test/resources/db/migration/V1_1__init_tables.sql
  src/test/resources/db/migration/V1_2__add_sequences.sql
  src/test/resources/db/migration/V1_3__alter_LRD.sql
  src/test/resources/db/migration/V1_4__Insert_LRD.sql
  src/test/resources/db/migration/V1_5__services.sql
  src/test/resources/db/migration/V1_6__excption_table.sql
  src/test/resources/db/migration/V1_7__audit_table.sql
  src/test/resources/db/migration/V1_8__alter_audit_exception_table.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-96
