Repository hmcts/rd-location-ref-api, pull requests merged in 2021-09, with the labels that each got.

#296 feat: RDCC-3230 Added flyway script to include row_id column in the exception table
  src/main/resources/db/migration/V1_15__alter_dataload_exception_records_add_row_id.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-296

#295 Add fortify implementation
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-295

#298 RDCC-3277 removing hardcoded config values
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  README.md
  charts/rd-location-ref-api/Chart.yaml
  charts/rd-location-ref-api/values.preview.template.yaml
  charts/rd-location-ref-api/values.yaml
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/resources/application-test.yml
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-298

#299 feat: RDCC-3230 Added flyway script to include row_id column in the exception table
  src/main/resources/db/migration/V1_15__alter_dataload_exception_records_add_row_id.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-299
