Repository hmcts/rd-location-ref-api, pull requests merged in 2021-03, with the labels that each got.

#180 fix: RDCC-2507 Upgraded spring boot version to fix CVE CVE-2021-22112
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-180

#184 fix: Spring version upgrade for Tomcat CVE fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-184

#189 fix: RDCC-2632 fix Hikari issue
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-189

#190 RDCC-2632 Added loggers for hikari
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-190

#179 Provider pact test organisational services
  Jenkinsfile_CNP
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/lrdapi/IdamConsumerTest.java
  src/contractTest/java/uk/gov/hmcts/reform/lrdapi/provider/LrdApiProviderTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-179
