Repository hmcts/rd-location-ref-api, pull requests merged in 2021-12, with the labels that each got.

#316 RDCC-3768: Disabled fortify scan until further notice
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-316

#317 fix: RDCC-3773 patch log4j to the latest version
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-317

#318 fix: patch log4j to the 2.16.0 in all applications to fix CVE-2021-45046
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-318

#319 Feat:Changes made to fix bot PRs
  .dependabot/config.yml
  .github/dependabot.yml
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-319

#331 fix: CVE-2021-45105 by upgrading log4j to 2.17.0
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-331
