Repository hmcts/rd-location-ref-api, pull requests merged in 2021-07, with the labels that each got.

#268 fixed the security scan in nightly job
  audit.json
  security.sh
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-268

#267 Add auto-update config for PR branches
  .github/workflows/autoupdate.yml
Labels: DO NOT MERGE, ns:rd, prd:rd, rel:rd-location-ref-api-pr-267

#271 feat: RDCC-2972 Modified Functional test cases to test success scenarios
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationDetailsFunctionalTest.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/domain/BuildingLocation.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdBuildingLocationServiceImpl.java
  src/main/resources/db/migrationAks/V2_2__insert_building_location.sql
  src/test/java/uk/gov/hmcts/reform/lrdapi/domain/BuildingLocationTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-271

#272 updated service name for AAA7 to Damages
  src/main/resources/db/migration/V1_14__update_service_name_damages.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-272

#269 fix: RDCC-3047 Fixed Pact not being verified issue
  Jenkinsfile_CNP
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-269

#270 Fixed for defect RDCC-2918 and additional test cases added.
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/oidc/JwtGrantedAuthoritiesConverter.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/oidc/JwtGrantedAuthoritiesConverterTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-270

#274 RDCC-3011: Enhancement to the existing LRD building location API
  src/contractTest/java/uk/gov/hmcts/reform/lrdapi/provider/LrdApiProviderTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationDetailsFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/GetBuildingLocationIntegrationTest.java
  src/integrationTest/resources/db/testmigration/V1_10__insert_LRD.sql
  src/integrationTest/resources/db/testmigration/V1_11__insert_test_buildinglocations.sql
  src/integrationTest/resources/db/testmigration/V1_13__drop_and_alter_tables.sql
  src/integrationTest/resources/db/testmigration/V1_14__lrd_surrogate_key_changes.sql
  src/integrationTest/resources/db/testmigration/V1_15__insert_court_venues.sql
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiController.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/constants/LocationRefConstants.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/response/CourtVenueResponse.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdBuildingLocationResponse.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/domain/BuildingLocation.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/domain/Cluster.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/domain/CourtVenue.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/domain/Region.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/repository/BuildingLocationRepository.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/repository/ClusterRepository.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/ILrdBuildingLocationService.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdBuildingLocationServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtils.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiControllerGetBuildingLocationsTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiControllerTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/response/CourtVenueResponseTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/domain/BuildingLocationTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdBuildingLocationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtilsTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-274

#273 Feat: RDCC-3010; Enhancement to the existing LRD Region API
  src/contractTest/java/uk/gov/hmcts/reform/lrdapi/provider/LrdApiProviderTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveRegionDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/client/LrdApiClient.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/GetBuildingLocationIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveRegionDetailsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LrdApiClient.java
  src/integrationTest/resources/db/testmigration/V1_10__insert_LRD.sql
  src/integrationTest/resources/db/testmigration/V1_11__insert_test_buildinglocations.sql
  src/integrationTest/resources/db/testmigration/V1_12__static_table_inserts_and_audit_exception_creation.sql
  src/integrationTest/resources/db/testmigration/V1_15__insert_court_venues.sql
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiController.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/constants/LocationRefConstants.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/domain/Region.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/repository/RegionRepository.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/RegionService.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/RegionServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtils.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiControllerOrgServiceTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiControllerRegionDetailsTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/RegionServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtilsTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-273

#277 RDCC-2805_nightly_fix: creating PR
  audit.json
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/AuthorizationFunctionalTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-277

#278 RDCC-3141: fixed CVE
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-278

#280 added for s2s communication from jrd to lrd
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-280

#282 RDCC-3150 - Update repositories reference to Jitpack
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-282

#279 feat: RDCC-3012 Retrieve the court venue details based on the supplied attribute.
  audit.json
  src/contractTest/java/uk/gov/hmcts/reform/lrdapi/provider/LrdApiProviderTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenueDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/client/LrdApiClient.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/GetBuildingLocationIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenueDetailsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LrdApiClient.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/config/LaunchDarklyConfiguration.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdCourtVenueController.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/advice/ExceptionMapper.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/constants/LocationRefConstants.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdBuildingLocationResponse.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdCourtVenueResponse.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/domain/BuildingLocation.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/domain/Cluster.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/domain/CourtVenue.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/domain/Region.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/repository/CourtVenueRepository.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/CourtVenueService.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/FeatureToggleServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtils.java
  src/main/resources/db/migrationAks/V2_4__insert_court_venues_1.sql
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdCourtVenueControllerTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdCourtVenueResponseTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdCourtVenuesByServiceCodeResponseTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/domain/CourtVenueTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-279

#283 fix: Security scan reported issue
  audit.json
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-283
