Repository hmcts/rd-location-ref-api, pull requests merged in 2022-08, with the labels that each got.

#447 RDCC-5261: Upgrading postgresql to 42.4.1
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-447

#445 RDCC-5196 service code to allow numbers
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/constants/LocationRefConstants.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiControllerOrgServiceTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-445

#449 Add backstage configuration file
  catalog-info.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-449

#448 Refactor code to remove the hard coding
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-448
