Repository hmcts/rd-location-ref-api, pull requests merged in 2022-05, with the labels that each got.

#400 RDCC-4523 LRD Api : Induce Common Libs library in to Location Reference Data API by removing unwanted dependencies
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenueDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesBySearchStringFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveRegionDetailsFunctionalTest.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/util/FeatureConditionEvaluation.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtils.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-400

#401 RDCC-4523 Sonar Issues Fixes
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiController.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdCourtVenueController.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/constants/LocationRefConstants.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdCourtVenuesByServiceCodeResponse.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/domain/ServiceToCcdCaseTypeAssoc.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/oidc/JwtGrantedAuthoritiesConverter.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdBuildingLocationServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/RegionServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtils.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-401

#402 Common Lib : Implement the Lib segregation for API related to Bearer tokens and fortify libs
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/AuthorizationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/client/LrdApiClient.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/client/S2sClient.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/config/TestConfigProperties.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/idam/IdamOpenIdClient.java
  src/functionalTest/resources/application-functional.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-402

#406 Fix CVE CVE-2022-25647
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-406

#405 Feat:Changes made to fix app-insights issue
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-405

#409 RDCC-4690: Suppressing CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-409

#411 fix: Bumped spring dependencies version to 5.3.20
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-411

#415 feat: Added multi-architecture ACR Task template
  Dockerfile
  acb.tpl.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-415
