Repository hmcts/rd-location-ref-api, pull requests merged in 2022-04, with the labels that each got.

#396 RDCC-4402: CVE Fix
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-396

#398 Feat:Use the New Common Library in Location Reference Data
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenueDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesBySearchStringFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveRegionDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/SerenityTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/SerenityTestWithoutReporting.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/counter/TestCountListener.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/counter/TestCounter.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/SerenityExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/SerenityJUnitLifecycleAdapterExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/SerenityManualExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/SerenityReportExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/SerenityStepExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/page/PatchedManagedWebDriverAnnotatedField.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/page/SerenityPageExtension.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/page/TestConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/extension/page/TestMethodAnnotations.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/guice/JUnit5Module.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/serenity5/guice/JUnitInjectors.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-398

#399 LRD-Nightly build failure -25/04/2022
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-399

#394 JDK17 upgrade changes
  Dockerfile
  build.gradle
  docker-compose.yml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-394
