Repository hmcts/rd-location-ref-api, pull requests merged in 2022-09, with the labels that each got.

#451 fix: RDCC-5447 Suppress CVEs
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-451

#454 Added court_type_service_assoc record
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsIntegrationTest.java
  src/integrationTest/resources/db/testmigration/V1_21__update_Court_type_service_assoc.sql
  src/integrationTest/resources/db/testmigration/V1_5__services.sql
  src/main/resources/db/migration/V1_21__update_Court_type_service_assoc.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-454

#458 Nightly Fix: Updating security.sh
  security.sh
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-458
