Repository hmcts/rd-location-ref-api, pull requests merged in 2022-10, with the labels that each got.

#467 RDCC - 5473 <Building location details search api changes>
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/lrdapi/provider/LrdApiProviderTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationDetailsBySearchFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/util/FeatureToggleConditionExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationBySearchStringTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LrdApiClient.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiController.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/constants/LocationRefConstants.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdBuildingLocationBySearchResponse.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/repository/BuildingLocationRepository.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/ILrdBuildingLocationService.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/FeatureToggleServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdBuildingLocationServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtils.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdApiControllerGetBuildingLocationsTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/response/LrdBuildingLocationBySearchResponseTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdBuildingLocationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtilsTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-467

#471 Create audit.json
  audit.json
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-471

#477 Views commit
  src/main/resources/db/migration/V1_23__create_views.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-477

#478 create read replica
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-478

#476 RDCC-5625: Location : MI Reporting - Schema and View creation
  src/main/resources/db/migration/V1_22__lrd_mi_reporting.sql
  src/main/resources/db/migration/V1_23__create_views.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-476

#479 RDCC-5729
  infrastructure/aat.tfvars
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-479

#473 RDCC-5662: Location : Court Venue Type ahead API to support hyphens
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesBySearchStringFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenueDetailsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesBySearchStringIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeIntegrationTest.java
  src/integrationTest/resources/db/testmigration/V1_15__insert_court_venues.sql
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/constants/LocationRefConstants.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtils.java
  src/main/resources/db/migrationAks/V2_5__insert_court_venues_2.sql
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdCourtVenueControllerTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-473
