Repository hmcts/rd-location-ref-api, pull requests merged in 2022-11, with the labels that each got.

#480 RDCC-5778: Upgrading `tomcat` to version `9.0.68`
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-480

#481 creating replica database in prod environment
  infrastructure/prod.tfvars
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-481

#483 creating read replica - ithc
  infrastructure/ithc.tfvars
  infrastructure/perftest.tfvars
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-483

#484 Feat:Containerisation of integration test cases
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveRegionDetailsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LocationRefApiPostgresqlContainer.java
  src/integrationTest/resources/application-test.yml
  src/integrationTest/resources/db/testmigration/V1_14__lrd_surrogate_key_changes.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-484

#485 Upgrade Terraform version 1.3.X :: RDCC-5894
  infrastructure/.terraform-version
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-485

#486 Upgrade Terraform and helm :: RDCC-5894
  charts/rd-location-ref-api/Chart.yaml
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-486

#489 CVE Fix for Postgresql
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-489
