Repository hmcts/rd-location-ref-api, pull requests merged in 2022-06, with the labels that each got.

#416 config: RDCC-4798 Configured renovate
  renovate.json
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-416

#413 Feat:To handle 500 HTTP responses
  src/main/java/uk/gov/hmcts/reform/lrdapi/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/config/SecurityEndpointFilter.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/advice/UnauthorizedException.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/repository/IdamRepository.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/advice/UnauthorizedExceptionTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/repository/IdamRepositoryTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-413

#417 Feat:RDCC-4676:Changes made to Auto merge depend Bot script w.r.t Renovate
  .github/workflows/combine-prs.yml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-417

#423 LRD : Testing using MRD test files for Location Reference Data
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveRegionDetailsFunctionalTest.java
  src/main/resources/db/migration/V1_19__Insert_mrd_changes_records.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-423

#434 RDCC-4876 : Testing using MRD test files for Location Reference Data
  src/main/resources/db/migration/V1_19__Insert_mrd_changes_records.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-434

#419 RDCC-4849: Collating DependaBot PRs
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-419

#435 RDCC-4898 Delete dependabot yaml file
  .github/dependabot.yml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-435

#436 RDCC-4887: Location - Update Region based on the new OPT Codes
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveRegionDetailsFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveRegionDetailsIntegrationTest.java
  src/integrationTest/resources/db/testmigration/V1_19__update_region_table.sql
  src/main/resources/db/migration/V1_20__update_region_table.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-436

#439 RDCC-5007: Adding Suppression for `CVE-2022-34305`
  charts/rd-location-ref-api/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-439
