Repository hmcts/rd-location-ref-api, pull requests merged in 2023-03, with the labels that each got.

#521 [RDCC-6452]Fix for failure of Nightly build
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-521

#522 [RDCC-6452]Fix for failure of Nightly build
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-522

#524 RDCC-6464: Adding Suppression for `CVE-2023-24998`
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-524

#519 RDCC-6421- renovate.json update.
  .github/renovate.json
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-519

#526 Nightly build failure due to expectation change
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationDetailsFunctionalTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-526

#525 RDCC-6469 Upgrade Libs
  build.gradle
  infrastructure/.terraform-version
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, no-changes, rel:rd-location-ref-api-pr-525

#523 Feat:Address CVEs in all Reference Data repositories - Location Reference Data
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-523

#513 RDCC-6344 Fetch court venue based on ePIMS ID and Court Type
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenueDetailsFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenueDetailsIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdCourtVenueController.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/constants/LocationRefConstants.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/repository/CourtVenueRepository.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/CourtVenueService.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtils.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdCourtVenueControllerTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/util/ValidationUtilsTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-513

#539 RDCC-6611: suppress CVE-2022-1471
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-539

#540 Nightly build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-540

#542 Nightly build failure
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-542
