Repository hmcts/rd-location-ref-api, pull requests merged in 2023-04, with the labels that each got.

#545 Fix nightly build with audit.json change
  audit.json
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-545

#546 Fix nightly build with audit.json change
  audit.json
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-546

#547 Addresses night build failure
  audit.json
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-547

#548 DTSRD-235 - update build.gradle for verifying pact and publish results
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-548

#552 Addresses CVE-2023-20863
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-552
