Repository hmcts/rd-location-ref-api, pull requests merged in 2023-06, with the labels that each got.

#563 DTSRD-556: fix CVE-2023-20883
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-563

#564 Update renovate
  renovate.json
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-564

#565 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-565
