Repository hmcts/rd-location-ref-api, pull requests merged in 2023-05, with the labels that each got.

#543 Upgraded to gradle wrapper 7.4.2
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-543

#554 addresses CVE-2023-20873, CVE-2023-20862
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-554

#553 EqualsIgnoreCase in func tests
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeFunctionalTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-553

#555 Addressed CVE-2021-22044
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-555

#557 DTSRD-261: tests
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesBySearchStringIntegrationTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdCourtVenueControllerTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-557

#560 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-560

#558 LRD: Test Cases can be clubbed as Parameterised tests
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsIntegrationTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/CourtVenueServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/LrdBuildingLocationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/lrdapi/service/impl/RegionServiceImplTest.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-558
