Repository hmcts/rd-location-ref-api, pull requests merged in 2023-11, with the labels that each got.

#657 DTSRD-1466.Updating schema parameter with hibernate
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-657

#549 Feat:Changes made to enhance wiremock response
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/LrdAuthorizationEnabledIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/IntegrationTestOidcSecurityConfig.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/WireMockUtil.java
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-549

#661 Update acb.tpl.yaml
  acb.tpl.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-661
