Repository hmcts/rd-location-ref-api, pull requests merged in 2024-12, with the labels that each got.

#878 Recreate spring-batch tables
  src/main/resources/db/migration/V1_30__recreate_spring_batch_tables.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-878

#881 CME-250: Disable sync to ITHC for database monitoring testing
  Jenkinsfile_CNP
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-881

#880 CME-250: Database monitoring and alerting on RD repositories
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-location-ref-api-pr-880, ithc/add-or-update
