Repository hmcts/rd-location-ref-api, pull requests merged in 2024-04, with the labels that each got.

#709 FIX AZURE EXTENSIONS
  Jenkinsfile_CNP
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, rel:rd-location-ref-api-pr-709

#702 FIX AZURE EXTENSIONS
  Jenkinsfile_CNP
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-702, aat/add-or-update

#703 DTSRD-2442: PI33 Configure spot instances in non-production
  charts/rd-location-ref-api/Chart.yaml
  charts/rd-location-ref-api/values.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-703

#743 DTSRD-2505: sync both ref-api and datalod reposiories
  src/integrationTest/resources/db/testmigration/V1_22__lrd_mi_reporting.sql
  src/integrationTest/resources/db/testmigration/V1_23__create_views.sql
  src/integrationTest/resources/db/testmigration/V1_24__alter_tables_add_columns.sql
  src/main/resources/db/migration/V1_25__alter_tables_add_columns.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-743

#750 Update pitest plugin
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-750
