Repository hmcts/rd-location-ref-api, pull requests merged in 2024-09, with the labels that each got.

#817 Trigger master pipeline
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-817

#818 DTSRD-3357
  Dockerfile
  acb.tpl.yaml
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-818

#820 AppInsights issue after Java 21 upgrade
  Dockerfile
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-820

#819 DTSRD-3066: CHG5017234 - Location data - Amend the unique key in court venue
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenueDetailsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeIntegrationTest.java
  src/integrationTest/resources/db/testmigration/V1_10__insert_LRD.sql
  src/integrationTest/resources/db/testmigration/V1_11__insert_test_buildinglocations.sql
  src/integrationTest/resources/db/testmigration/V1_15__insert_court_venues.sql
  src/integrationTest/resources/db/testmigration/V1_26__insert_court_venues.sql
  src/integrationTest/resources/db/testmigration/V1_27__alter_table_court_venue_constraints.sql
  src/main/resources/db/migration/V1_27__alter_table_court_venue_constraints.sql
  src/main/resources/db/migrationAks/V2_2__insert_building_location.sql
  src/main/resources/db/migrationAks/V2_3__insert_court_venues.sql
  src/main/resources/db/migrationAks/V2_4__insert_court_venues_1.sql
  src/main/resources/db/migrationAks/V2_5__insert_court_venues_2.sql
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-819, enable_keep_helm
