Repository hmcts/rd-location-ref-api, pull requests merged in 2024-10, with the labels that each got.

#822 DTSRD-3477 Fix local DependencyCheck, version upgraded to 10.0.3
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-822

#824 DTSRD-3562 Swagger Publishing
  .github/workflows/swagger.yml
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/config/SwaggerPublisherTest.java
  src/main/resources/application.yaml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-824

#826 DTSRD-3578
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-826

#830 DTSRD-3583 Mutation Tests BootClassPathSupported False Error - junit5…
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-830

#827 DTSRD-3580 Jenkins Test Reports to Publish on Failure
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-827

#844 DTSRD-3619
  build.gradle
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-844
