Repository hmcts/rd-location-ref-api, pull requests merged in 2024-06, with the labels that each got.

#766 DTSRD-2810
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:rd, prd:rd, rel:rd-location-ref-api-pr-766

#767 Update azurerm
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, rel:rd-location-ref-api-pr-767

#771 DTSRD-2845: Resize PG flexible server instance
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-location-ref-api-pr-771
