Repository hmcts/rd-location-ref-api, pull requests merged in 2025-01, with the labels that each got.

#883 CME-250: Database monitoring and alerting on RD repositories
  Jenkinsfile_CNP
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:rd, prd:rd, aat/add-or-update, prod/add-or-update, rel:rd-location-ref-api-pr-883

#884 CME-299: Update azurerm
  infrastructure/terraform.tf
Labels: ns:rd, prd:rd, aat/destroy, prod/destroy, rel:rd-location-ref-api-pr-884

#891 Update to spring-boot 3.3.7
  build.gradle
Labels: ns:rd, prd:rd

#894 DTSRD-4065
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/lrdapi/provider/LrdApiProviderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/LrdAuthorizationEnabledIntegrationTest.java
Labels: ns:rd, prd:rd

#879 CME-199-bump-rd-commons-lib
  .travis.yml
  Dockerfile
  README.md
  bin/init.sh
  build.gradle
  database/Dockerfile
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/variables.tf
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/AuthorizationFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationDetailsBySearchFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenueDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesBySearchStringFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveRegionDetailsFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/lrdapi/util/FeatureToggleConditionExtension.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationBySearchStringTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveBuildingLocationIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenueDetailsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesBySearchStringIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveCourtVenuesByServiceCodeIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveOrgServiceDetailsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/RetrieveRegionDetailsIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/config/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LocationRefApiPostgresqlContainer.java
  src/integrationTest/java/uk/gov/hmcts/reform/lrdapi/util/LrdApiClient.java
  src/integrationTest/resources/application-test.yml
  src/main/java/uk/gov/hmcts/reform/lrdapi/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/lrdapi/controllers/LrdCourtVenueController.java
  src/smokeTest/java/uk/gov/hmcts/reform/lrdapi/SmokeTest.java
  web.config
Labels: ns:rd, prd:rd, aat/no-changes, prod/no-changes, enable_keep_helm, rel:rd-location-ref-api-pr-879
